//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

code unsigned char neg_sign [] = {
0x00, 0x08, 0x08, 0x08, 0x00,
};
